<?php

use Illuminate\Database\Seeder;

class AnimalTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('animal')->delete();
        
        \DB::table('animal')->insert(array (
            0 => 
            array (
                'animal_id' => 'MBG0004',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'COLORADA',
                'animal_peso' => '297',
                'animal_raza' => 9,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2019-01-09',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:38:18',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '26845822',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '85',
            ),
            1 => 
            array (
                'animal_id' => 'MES0023',
                'animal_madre' => 'MES0012',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'COLORADA CLARA',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 3,
                'animal_nacimiento' => '2021-11-06',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:34:39',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899875',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '94',
            ),
            2 => 
            array (
                'animal_id' => 'MES0003',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'AHUMADA',
                'animal_peso' => '320',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2016-04-14',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:10:44',
                'updated_at' => '2022-06-20 11:10:44',
                'codigo_bien' => '8237046',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '75',
            ),
            3 => 
            array (
                'animal_id' => 'MES0004',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'COLORADA PINTA',
                'animal_peso' => '405',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2016-04-28',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:11:53',
                'updated_at' => '2022-06-20 11:11:53',
                'codigo_bien' => '8237045',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '76',
            ),
            4 => 
            array (
                'animal_id' => 'MES0005',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'COLORADA',
                'animal_peso' => '406',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2016-05-11',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:13:06',
                'updated_at' => '2022-06-20 11:13:06',
                'codigo_bien' => '8237044',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '77',
            ),
            5 => 
            array (
                'animal_id' => 'MES0006',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA',
                'animal_peso' => '418',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2011-01-01',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:14:14',
                'updated_at' => '2022-06-20 11:14:14',
                'codigo_bien' => '3991655',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '52',
            ),
            6 => 
            array (
                'animal_id' => 'MES0007',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'COLORADA',
                'animal_peso' => '394',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2010-06-15',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:15:46',
                'updated_at' => '2022-06-20 11:15:46',
                'codigo_bien' => '3991661',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '58',
            ),
            7 => 
            array (
                'animal_id' => 'MES0008',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'ROJA',
                'animal_peso' => '460',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2010-11-09',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:17:06',
                'updated_at' => '2022-06-20 11:17:06',
                'codigo_bien' => '3991662',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '60',
            ),
            8 => 
            array (
                'animal_id' => 'MES0009',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA',
                'animal_peso' => '538',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2013-06-03',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:18:46',
                'updated_at' => '2022-06-20 11:18:46',
                'codigo_bien' => '3991675',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '63',
            ),
            9 => 
            array (
                'animal_id' => 'MBG0001',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA',
                'animal_peso' => '334',
                'animal_raza' => 9,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2018-09-26',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 10:56:54',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '26775479',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '82',
            ),
            10 => 
            array (
                'animal_id' => 'MES0024',
                'animal_madre' => 'MES0006',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'CAFÉ',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 1,
                'animal_nacimiento' => '2021-12-08',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:41:00',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899874',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '95',
            ),
            11 => 
            array (
                'animal_id' => 'MES0014',
                'animal_madre' => 'MES0006',
                'animal_padre' => 'IA-MAFIOSO Gyr h',
                'animal_color' => 'CAFÉ OSCURA',
                'animal_peso' => '130',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 3,
                'animal_nacimiento' => '2020-04-25',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:46:14',
                'updated_at' => '2022-06-20 11:46:14',
                'codigo_bien' => '31167253',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '88',
            ),
            12 => 
            array (
                'animal_id' => 'MES0025',
                'animal_madre' => 'MES0009',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'CAFÉ-CENIZA',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 1,
                'animal_nacimiento' => '2021-12-31',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:44:59',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899873',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '96',
            ),
            13 => 
            array (
                'animal_id' => 'MES0031',
                'animal_madre' => 'GYR0001',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'BLANCO PINTO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2021-03-28',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:13:23',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899885',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '177',
            ),
            14 => 
            array (
                'animal_id' => 'MES0032',
                'animal_madre' => 'MES0001',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'NEGRO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2021-03-29',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:15:12',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899884',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '178',
            ),
            15 => 
            array (
                'animal_id' => 'MES0033',
                'animal_madre' => 'MES0007',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'NEGRO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2021-05-13',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:17:09',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899883',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '179',
            ),
            16 => 
            array (
                'animal_id' => 'MES0015',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRO',
                'animal_peso' => '280',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2019-07-05',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:06:34',
                'updated_at' => '2022-06-20 12:06:34',
                'codigo_bien' => '30682275',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '166',
            ),
            17 => 
            array (
                'animal_id' => 'MES0016',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'BLANCO',
                'animal_peso' => '241',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2019-07-11',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:08:31',
                'updated_at' => '2022-06-20 12:08:31',
                'codigo_bien' => '30682274',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '167',
            ),
            18 => 
            array (
                'animal_id' => 'MES0017',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'BLANCO',
                'animal_peso' => '190',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2019-08-24',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:09:32',
                'updated_at' => '2022-06-20 12:09:32',
                'codigo_bien' => '30682273',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '168',
            ),
            19 => 
            array (
                'animal_id' => 'MES0018',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'CAFÉ',
                'animal_peso' => '170',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2019-09-09',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:10:53',
                'updated_at' => '2022-06-20 12:10:53',
                'codigo_bien' => '30682271',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '170',
            ),
            20 => 
            array (
                'animal_id' => 'MES0019',
                'animal_madre' => 'MES0003',
                'animal_padre' => 'BRA0001',
                'animal_color' => 'CAFÉ',
                'animal_peso' => '85',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 3,
                'animal_nacimiento' => '2020-06-30',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:16:31',
                'updated_at' => '2022-06-20 12:16:31',
                'codigo_bien' => '31167248',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '90',
            ),
            21 => 
            array (
                'animal_id' => 'MES0026',
                'animal_madre' => 'MES0011',
                'animal_padre' => 'IA-MAFIOSO GYRH',
                'animal_color' => 'CAFÉ AMARILLO',
                'animal_peso' => '168',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2020-04-23',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:53:25',
                'updated_at' => '2022-06-20 12:53:25',
                'codigo_bien' => '31167255',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '171',
            ),
            22 => 
            array (
                'animal_id' => 'MES0027',
                'animal_madre' => 'MES0010',
                'animal_padre' => 'IA-MAFIOSO GYRH',
                'animal_color' => 'CAFÉ',
                'animal_peso' => '137',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2020-04-24',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:57:31',
                'updated_at' => '2022-06-20 12:57:31',
                'codigo_bien' => '31167254',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '172',
            ),
            23 => 
            array (
                'animal_id' => 'MES0028',
                'animal_madre' => 'HOL0001',
                'animal_padre' => 'IA-MAFIOSO GYRH',
                'animal_color' => 'CAFÉ',
                'animal_peso' => '115',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2020-04-30',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:02:35',
                'updated_at' => '2022-06-20 13:02:35',
                'codigo_bien' => '31167251',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '174',
            ),
            24 => 
            array (
                'animal_id' => 'MES0029',
                'animal_madre' => 'MES0012',
                'animal_padre' => 'BRA0001',
                'animal_color' => 'BLANCO CON CAFÉ',
                'animal_peso' => '145',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2020-06-24',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:09:13',
                'updated_at' => '2022-06-20 13:09:13',
                'codigo_bien' => '31167249',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '175',
            ),
            25 => 
            array (
                'animal_id' => 'MES0038',
                'animal_madre' => 'MES0003',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'COLORADO CON LUCERO',
                'animal_peso' => '35',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 1,
                'animal_nacimiento' => '2022-02-20',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:25:53',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '0000000001',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '184',
            ),
            26 => 
            array (
                'animal_id' => 'MES0041',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2020-06-05',
                'animal_imagen' => NULL,
                'animal_estado' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 14:00:44',
                'updated_at' => '2022-06-20 14:02:06',
                'codigo_bien' => '31167250',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '89',
            ),
            27 => 
            array (
                'animal_id' => 'MES0039',
                'animal_madre' => 'MES0011',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'NEGRO',
                'animal_peso' => '36',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 1,
                'animal_nacimiento' => '2022-03-25',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:27:47',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '0000000002',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '185',
            ),
            28 => 
            array (
                'animal_id' => 'MES0030',
                'animal_madre' => 'GYR0002',
                'animal_padre' => 'BRA0001',
                'animal_color' => 'CAFÉ',
                'animal_peso' => '85',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2020-07-08',
                'animal_imagen' => NULL,
                'animal_estado' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:11:35',
                'updated_at' => '2022-06-20 14:04:39',
                'codigo_bien' => '34899886',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '176',
            ),
            29 => 
            array (
                'animal_id' => 'MES0042',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2019-08-21',
                'animal_imagen' => NULL,
                'animal_estado' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 14:05:28',
                'updated_at' => '2022-06-20 14:06:12',
                'codigo_bien' => '30682272',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '169',
            ),
            30 => 
            array (
                'animal_id' => 'MES0002',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'ROJA',
                'animal_peso' => '370',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2016-05-19',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:09:16',
                'updated_at' => '2022-06-22 19:43:36',
                'codigo_bien' => '8237043',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '78',
            ),
            31 => 
            array (
                'animal_id' => 'MES0001',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA PINTA',
                'animal_peso' => '377',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2016-08-08',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 10:55:27',
                'updated_at' => '2022-06-20 14:21:20',
                'codigo_bien' => '9969939',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '79',
            ),
            32 => 
            array (
                'animal_id' => 'MES0040',
                'animal_madre' => 'MES0010',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'CAFÉ OSCURO',
                'animal_peso' => '25',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 1,
                'animal_nacimiento' => '2022-03-28',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:29:02',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '0000000003',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '186',
            ),
            33 => 
            array (
                'animal_id' => 'MBH0001',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA CON BLANCO',
                'animal_peso' => '295',
                'animal_raza' => 10,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 3,
                'animal_nacimiento' => '2019-01-11',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:42:02',
                'updated_at' => '2022-06-20 11:42:02',
                'codigo_bien' => '26845824',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '87',
            ),
            34 => 
            array (
                'animal_id' => 'MGH0001',
                'animal_madre' => 'MES0013',
                'animal_padre' => 'IA-MAFIOSO GYRH',
                'animal_color' => 'BLANCO',
                'animal_peso' => '120',
                'animal_raza' => 11,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2020-04-28',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:01:04',
                'updated_at' => '2022-06-20 13:01:04',
                'codigo_bien' => '31167252',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '173',
            ),
            35 => 
            array (
                'animal_id' => 'GYR0002',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'CAFÉ',
                'animal_peso' => '269',
                'animal_raza' => 8,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2017-05-28',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:07:38',
                'updated_at' => '2022-06-20 15:44:11',
                'codigo_bien' => '19022241',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '80',
            ),
            36 => 
            array (
                'animal_id' => 'MES0036',
                'animal_madre' => 'MES0002',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'COLORADO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2021-09-15',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:22:32',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899880',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '182',
            ),
            37 => 
            array (
                'animal_id' => 'MES0021',
                'animal_madre' => 'MES0005',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'CAFÉ',
                'animal_peso' => '145',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 3,
                'animal_nacimiento' => '2021-04-24',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:23:08',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899877',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '92',
            ),
            38 => 
            array (
                'animal_id' => 'MES0020',
                'animal_madre' => 'MES0008',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'PINTA',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 3,
                'animal_nacimiento' => '2021-03-29',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:21:05',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899878',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '91',
            ),
            39 => 
            array (
                'animal_id' => 'MES0034',
                'animal_madre' => 'MBG0001',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'NEGRO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 2,
                'animal_nacimiento' => '2021-07-19',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:19:00',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899882',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '180',
            ),
            40 => 
            array (
                'animal_id' => 'BRA0001',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'desconocido',
                'animal_peso' => '0',
                'animal_raza' => 7,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2017-01-06',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:14:13',
                'updated_at' => '2022-06-20 16:33:40',
                'codigo_bien' => '26845940',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '162',
            ),
            41 => 
            array (
                'animal_id' => 'MES0010',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'CAFÉ',
                'animal_peso' => '370',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2013-06-13',
                'animal_imagen' => '',
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:23:43',
                'updated_at' => '2022-06-21 08:28:13',
                'codigo_bien' => '3991678',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '70',
            ),
            42 => 
            array (
                'animal_id' => 'MES0012',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'ROJA',
                'animal_peso' => '390',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2013-01-05',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:31:23',
                'updated_at' => '2022-06-21 10:44:10',
                'codigo_bien' => '3991687',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '73',
            ),
            43 => 
            array (
                'animal_id' => 'HOL0001',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA',
                'animal_peso' => '440',
                'animal_raza' => 3,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2013-06-24',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:20:16',
                'updated_at' => '2022-06-22 19:35:58',
                'codigo_bien' => '3991697',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '69',
            ),
            44 => 
            array (
                'animal_id' => 'MES0035',
                'animal_madre' => 'MES0013',
                'animal_padre' => 'inseminación',
                'animal_color' => 'CAFÉ NEGRUZCO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2021-09-13',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:20:43',
                'updated_at' => '2022-06-20 14:16:31',
                'codigo_bien' => '34899881',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '181',
            ),
            45 => 
            array (
                'animal_id' => 'MES0013',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'CAFÉ OSCURA',
                'animal_peso' => '395',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2014-02-17',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:33:08',
                'updated_at' => '2022-06-21 19:22:33',
                'codigo_bien' => '3991688',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '74',
            ),
            46 => 
            array (
                'animal_id' => 'MES0037',
                'animal_madre' => 'MBG0004',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'COLORADO',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 1,
                'animal_nacimiento' => '2021-12-11',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:23:49',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899879',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '183',
            ),
            47 => 
            array (
                'animal_id' => 'MBG0003',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA',
                'animal_peso' => '241',
                'animal_raza' => 9,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2019-01-07',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:37:14',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '26845821',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '84',
            ),
            48 => 
            array (
                'animal_id' => 'MBG0009',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRO',
                'animal_peso' => '490',
                'animal_raza' => 9,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2018-05-01',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:05:00',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '26845941',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '163',
            ),
            49 => 
            array (
                'animal_id' => 'MBG0005',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'AMARILLA',
                'animal_peso' => '264',
                'animal_raza' => 9,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2019-01-11',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:39:42',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '26845823',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '86',
            ),
            50 => 
            array (
                'animal_id' => 'MBG0006',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'TRIGRILLO',
                'animal_peso' => '320',
                'animal_raza' => 9,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2018-09-21',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:56:51',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '26775478',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '161',
            ),
            51 => 
            array (
                'animal_id' => 'MBG0007',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRO',
                'animal_peso' => '257',
                'animal_raza' => 9,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2019-03-03',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:57:53',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '28806458',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '164',
            ),
            52 => 
            array (
                'animal_id' => 'MBG0008',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'CAFÉ OSCURO',
                'animal_peso' => '242',
                'animal_raza' => 9,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2019-03-12',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:03:48',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '28806459',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '165',
            ),
            53 => 
            array (
                'animal_id' => 'MES0022',
                'animal_madre' => 'HOL0001',
                'animal_padre' => 'MBG0009',
                'animal_color' => 'NEGRA',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 3,
                'animal_nacimiento' => '2021-05-03',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:32:00',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '34899876',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '93',
            ),
            54 => 
            array (
                'animal_id' => 'MBG0010',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRO',
                'animal_peso' => '0',
                'animal_raza' => 9,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2011-04-14',
                'animal_imagen' => NULL,
                'animal_estado' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 13:30:58',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '3991660',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '56',
            ),
            55 => 
            array (
                'animal_id' => 'MBG0012',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 9,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2017-04-15',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:20:40',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '19023417',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '159',
            ),
            56 => 
            array (
                'animal_id' => 'MBG0013',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 9,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2017-05-05',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:21:17',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '19023418',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '160',
            ),
            57 => 
            array (
                'animal_id' => 'MES0011',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'NEGRA',
                'animal_peso' => '470',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2013-07-01',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:29:52',
                'updated_at' => '2022-06-21 09:13:31',
                'codigo_bien' => '3991680',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '71',
            ),
            58 => 
            array (
                'animal_id' => 'MES0043',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2011-01-01',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:22:12',
                'updated_at' => '2022-06-20 16:29:13',
                'codigo_bien' => '3991645',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '3',
            ),
            59 => 
            array (
                'animal_id' => 'MES0044',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2011-01-01',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:22:50',
                'updated_at' => '2022-06-20 16:29:56',
                'codigo_bien' => '3991657',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '53',
            ),
            60 => 
            array (
                'animal_id' => 'MES0045',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2011-01-01',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:23:52',
                'updated_at' => '2022-06-20 16:30:53',
                'codigo_bien' => '3991658',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '54',
            ),
            61 => 
            array (
                'animal_id' => 'MES0046',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2016-05-26',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:24:28',
                'updated_at' => '2022-06-20 16:32:02',
                'codigo_bien' => '8237042',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '157',
            ),
            62 => 
            array (
                'animal_id' => 'MES0047',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 1,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2011-11-23',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:25:01',
                'updated_at' => '2022-06-20 16:33:08',
                'codigo_bien' => '3991667',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '64',
            ),
            63 => 
            array (
                'animal_id' => 'MBG0002',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'CAFÉ',
                'animal_peso' => '241',
                'animal_raza' => 9,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2019-01-01',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:35:51',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '26845820',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '83',
            ),
            64 => 
            array (
                'animal_id' => 'MBG0011',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'negro',
                'animal_peso' => '0',
                'animal_raza' => 9,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2016-05-04',
                'animal_imagen' => NULL,
                'animal_estado' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 16:19:49',
                'updated_at' => '2022-06-22 22:02:38',
                'codigo_bien' => '8788039',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '158',
            ),
            65 => 
            array (
                'animal_id' => 'GYR0001',
                'animal_madre' => NULL,
                'animal_padre' => NULL,
                'animal_color' => 'CENIZA PINTA',
                'animal_peso' => '370',
                'animal_raza' => 8,
                'animal_sexo' => 'Hembra',
                'animal_categoria' => 5,
                'animal_nacimiento' => '2017-06-14',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 11:06:03',
                'updated_at' => '2022-06-21 08:25:53',
                'codigo_bien' => '19022242',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '81',
            ),
            66 => 
            array (
                'animal_id' => 'inseminación',
                'animal_madre' => '',
                'animal_padre' => '',
                'animal_color' => 'CAFÉ',
                'animal_peso' => '0',
                'animal_raza' => 0,
                'animal_sexo' => 'Macho',
                'animal_categoria' => 4,
                'animal_nacimiento' => '2020-06-30',
                'animal_imagen' => NULL,
                'animal_estado' => 1,
                'deleted_at' => NULL,
                'created_at' => '2022-06-20 12:16:31',
                'updated_at' => '2022-06-20 12:16:31',
                'codigo_bien' => '0',
                'animal_produccion' => 1,
                'animal_abierto' => false,
                'fecha_secado' => NULL,
                'animal_arete' => '0',
            ),
        ));
        
        
    }
}